#!/bin/sh

# This script based on
# http://www.deadman.org/sshscreen.php

# I use 2 aliases with this script:
# alias attach-tmux 'grabssh; tmux attach -d || tmux new'
# alias ssh         'source ~/bin/fixssh; /usr/bin/ssh'

[ -S $SSH_AUTH_SOCK ] || exit 1

SSHVARS='SSH_CLIENT SSH_TTY SSH_AUTH_SOCK SSH_CONNECTION'

case $SHELL in
*/bin/tcsh)
	RE='s/=/ "/;s/$/"/;s/^/setenv /'
	;;
*)
	RE='s/=/="/;s/$/"/;s/^/export /'
	;;
esac

mv $HOME/bin/fixssh $HOME/bin/fixssh_saved

for x in $SSHVARS; do
    (eval echo $x=\$$x) | sed "$RE"
done 1>$HOME/bin/fixssh

chmod +x $HOME/bin/fixssh
